### ISSUE TITLE
有没有直接发布的版本？

### ISSUE THREAD

**Issue by ipcjs** [lotem/rimekit#1]
[这个页面](http://rime.im/blog/2013/08/28/spelling-algebra-debugger/)给的链接已经失效了。
我试图根据readme一步步自己编译一直报错。
所以想求个编译好的版本。

报错信息：

```
C:\GreenSoft\rimekit-develop\app.nw>npm install --python
npm WARN prefer global node-gyp@3.4.0 should be installed with -g

> node-marisa-trie@0.1.2 install C:\GreenSoft\rimekit-develop\app.nw\node_modules\node-marisa-trie
> node-gyp rebuild


C:\GreenSoft\rimekit-develop\app.nw\node_modules\node-marisa-trie>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\.
.\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: socket hang up
gyp ERR! stack     at TLSSocket.onHangUp (_tls_wrap.js:1092:19)
gyp ERR! stack     at TLSSocket.g (events.js:286:16)
gyp ERR! stack     at emitNone (events.js:91:20)
gyp ERR! stack     at TLSSocket.emit (events.js:185:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:975:12)
gyp ERR! stack     at _combinedTickCallback (internal/process/next_tick.js:74:11)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:98:9)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\GreenSoft\rimekit-develop\app.nw\node_modules\node-marisa-trie
gyp ERR! node -v v6.4.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok
npm WARN rimekit@0.1.0 No license field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--python"
npm ERR! node v6.4.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! node-marisa-trie@0.1.2 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-marisa-trie@0.1.2 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the node-marisa-trie package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs node-marisa-trie
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls node-marisa-trie
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\GreenSoft\rimekit-develop\app.nw\npm-debug.log
```

**Comment by matthewwo** [comment]
求救呀 有沒有?

**Comment by Shen-Linwood** [comment]
同求
